# Generated by Django 4.2.6 on 2024-01-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='description',
            field=models.CharField(default='', max_length=201),
        ),
        migrations.AddField(
            model_name='query',
            name='title',
            field=models.CharField(default='', max_length=51),
        ),
    ]
