# Generated by Django 4.2.6 on 2023-12-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasketch',
            name='sketch',
            field=models.BinaryField(editable=True),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('stream', 'name'), name='unique_names_tags'),
        ),
        migrations.AddConstraint(
            model_name='type',
            constraint=models.UniqueConstraint(fields=('stream', 'name'), name='unique_names_types'),
        ),
    ]
