# Generated by Django 4.2.6 on 2023-12-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_datasketch_sketch_alter_datastream_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_form', models.JSONField()),
                ('dnf', models.JSONField(editable=False)),
            ],
        ),
    ]
