# Generated by Django 4.2.6 on 2023-12-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tag_category_alter_tag_stream_alter_type_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='unit',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
