# fly.toml app configuration file generated for datastream-analytics-backend on 2023-11-08T23:51:05+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "datastream-analytics-backend"
primary_region = "waw"
console_command = "/code/manage.py shell"
swap_size_mb = 512

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
